// ============================================================================
// The "?" command pack. Lightweight, self-contained utility/fun/text/math
// commands that run on the "?" prefix (e.g. ?reverse hello). They don't register
// as slash commands, so they don't count against Discord's 100 top-level cap —
// which is how we grow the command count without breaking registration.
//
// Each command: { name, aliases?, category, description, run(ctx) -> string|void }
// ctx = { args (string after the name), argv (whitespace split), message }
// A returned string is sent as a reply; commands may also reply themselves.
// ============================================================================

const rint = (a, b) => Math.floor(Math.random() * (b - a + 1)) + a;
const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];
const need = (s, usage) => { if (!s || !s.trim()) throw new Error(`Usage: \`${usage}\``); return s.trim(); };
const nums = (argv) => argv.map(Number).filter((n) => !Number.isNaN(n));

const MORSE = { a: '.-', b: '-...', c: '-.-.', d: '-..', e: '.', f: '..-.', g: '--.', h: '....', i: '..', j: '.---', k: '-.-', l: '.-..', m: '--', n: '-.', o: '---', p: '.--.', q: '--.-', r: '.-.', s: '...', t: '-', u: '..-', v: '...-', w: '.--', x: '-..-', y: '-.--', z: '--..', 0: '-----', 1: '.----', 2: '..---', 3: '...--', 4: '....-', 5: '.....', 6: '-....', 7: '--...', 8: '---..', 9: '----.' };
const UNMORSE = Object.fromEntries(Object.entries(MORSE).map(([k, v]) => [v, k]));
const ROMANS = [[1000, 'M'], [900, 'CM'], [500, 'D'], [400, 'CD'], [100, 'C'], [90, 'XC'], [50, 'L'], [40, 'XL'], [10, 'X'], [9, 'IX'], [5, 'V'], [4, 'IV'], [1, 'I']];

const COMMANDS = [
  // ---------------- TEXT (category: qtext) ----------------
  { name: 'reverse', category: 'qtext', description: 'Reverse your text', run: ({ args }) => [...need(args, '?reverse <text>')].reverse().join('') },
  { name: 'upper', category: 'qtext', description: 'UPPERCASE your text', run: ({ args }) => need(args, '?upper <text>').toUpperCase() },
  { name: 'lower', category: 'qtext', description: 'lowercase your text', run: ({ args }) => need(args, '?lower <text>').toLowerCase() },
  { name: 'title', category: 'qtext', description: 'Title Case Your Text', run: ({ args }) => need(args, '?title <text>').replace(/\b\w/g, (c) => c.toUpperCase()) },
  { name: 'clap', category: 'qtext', description: '👏 Put 👏 claps 👏 between 👏 words', run: ({ args }) => need(args, '?clap <text>').split(/\s+/).join(' 👏 ') },
  { name: 'mock', category: 'qtext', description: 'sPoNgEbOb mOcKiNg text', run: ({ args }) => [...need(args, '?mock <text>')].map((c, i) => (i % 2 ? c.toUpperCase() : c.toLowerCase())).join('') },
  { name: 'owo', aliases: ['owoify'], category: 'qtext', description: 'OwO-ify your text', run: ({ args }) => need(args, '?owo <text>').replace(/[rl]/g, 'w').replace(/[RL]/g, 'W').replace(/n([aeiou])/g, 'ny$1') + ' owo' },
  { name: 'vaporwave', aliases: ['aesthetic'], category: 'qtext', description: 'Ｆｕｌｌ－ｗｉｄｔｈ aesthetic', run: ({ args }) => [...need(args, '?vaporwave <text>')].map((c) => { const code = c.charCodeAt(0); return code >= 33 && code <= 126 ? String.fromCharCode(code + 0xfee0) : c === ' ' ? '　' : c; }).join('') },
  { name: 'spacer', aliases: ['space'], category: 'qtext', description: 's p a c e out text', run: ({ args }) => [...need(args, '?spacer <text>')].join(' ') },
  { name: 'leet', category: 'qtext', description: 'Convert to l33t sp34k', run: ({ args }) => need(args, '?leet <text>').replace(/[aeiost]/gi, (c) => ({ a: '4', e: '3', i: '1', o: '0', s: '5', t: '7' })[c.toLowerCase()]) },
  { name: 'rot13', category: 'qtext', description: 'ROT13 cipher a message', run: ({ args }) => need(args, '?rot13 <text>').replace(/[a-z]/gi, (c) => String.fromCharCode((c <= 'Z' ? 90 : 122) >= (c = c.charCodeAt(0) + 13) ? c : c - 26)) },
  { name: 'binary', category: 'qtext', description: 'Text → binary', run: ({ args }) => [...need(args, '?binary <text>')].map((c) => c.charCodeAt(0).toString(2).padStart(8, '0')).join(' ') },
  { name: 'unbinary', category: 'qtext', description: 'Binary → text', run: ({ args }) => need(args, '?unbinary <bits>').trim().split(/\s+/).map((b) => String.fromCharCode(parseInt(b, 2))).join('') },
  { name: 'morse', category: 'qtext', description: 'Text → Morse code', run: ({ args }) => [...need(args, '?morse <text>').toLowerCase()].map((c) => (c === ' ' ? '/' : MORSE[c] ?? '')).join(' ').trim() },
  { name: 'unmorse', category: 'qtext', description: 'Morse code → text', run: ({ args }) => need(args, '?unmorse <morse>').trim().split(' ').map((s) => (s === '/' ? ' ' : UNMORSE[s] ?? '')).join('') },
  { name: 'emojiletters', aliases: ['emojify'], category: 'qtext', description: 'Turn letters into 🇦 emoji letters', run: ({ args }) => [...need(args, '?emojiletters <text>').toLowerCase()].map((c) => (/[a-z]/.test(c) ? String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 97) + ' ' : c === ' ' ? '   ' : c)).join('') },
  { name: 'redact', category: 'qtext', description: '█████ redact your text', run: ({ args }) => need(args, '?redact <text>').replace(/\S/g, '█') },
  { name: 'reverwords', aliases: ['reversewords'], category: 'qtext', description: 'Reverse the word order', run: ({ args }) => need(args, '?reverwords <text>').split(/\s+/).reverse().join(' ') },
  { name: 'count', aliases: ['wc'], category: 'qtext', description: 'Count characters & words', run: ({ args }) => { const s = need(args, '?count <text>'); return `📊 ${[...s].length} characters, ${s.trim().split(/\s+/).length} words.`; } },

  // ---------------- MATH & CONVERT (category: qmath) ----------------
  { name: 'calc', aliases: ['math'], category: 'qmath', description: 'Evaluate a math expression', run: ({ args }) => { const e = need(args, '?calc <expression>'); if (!/^[-+*/%.()\d\s]+$/.test(e)) throw new Error('Only numbers and + - * / % ( ) allowed.'); const r = Function(`"use strict";return (${e})`)(); return `🧮 ${e} = **${r}**`; } },
  { name: 'roll', aliases: ['dice'], category: 'qmath', description: 'Roll dice, e.g. ?roll 2d6', run: ({ args }) => { const m = (args || '1d6').trim().match(/^(\d*)d(\d+)$/i); if (!m) throw new Error('Format: `?roll 2d6`'); const n = Math.min(100, +(m[1] || 1)); const s = Math.min(1000, +m[2]); const rolls = Array.from({ length: n }, () => rint(1, s)); return `🎲 [${rolls.join(', ')}] = **${rolls.reduce((a, b) => a + b, 0)}**`; } },
  { name: 'percent', aliases: ['pct'], category: 'qmath', description: '?percent 20 150 → 20% of 150', run: ({ argv }) => { const [p, v] = nums(argv); if (p == null || v == null) throw new Error('Usage: `?percent <pct> <value>`'); return `📈 ${p}% of ${v} = **${(p / 100) * v}**`; } },
  { name: 'sum', aliases: ['add'], category: 'qmath', description: 'Sum a list of numbers', run: ({ argv }) => { const n = nums(argv); if (!n.length) throw new Error('Usage: `?sum 1 2 3`'); return `➕ Sum = **${n.reduce((a, b) => a + b, 0)}**`; } },
  { name: 'avg', aliases: ['mean', 'average'], category: 'qmath', description: 'Average a list of numbers', run: ({ argv }) => { const n = nums(argv); if (!n.length) throw new Error('Usage: `?avg 1 2 3`'); return `📊 Average = **${(n.reduce((a, b) => a + b, 0) / n.length).toFixed(2)}**`; } },
  { name: 'c2f', category: 'qmath', description: 'Celsius → Fahrenheit', run: ({ argv }) => { const [c] = nums(argv); if (c == null) throw new Error('Usage: `?c2f 20`'); return `🌡️ ${c}°C = **${(c * 9 / 5 + 32).toFixed(1)}°F**`; } },
  { name: 'f2c', category: 'qmath', description: 'Fahrenheit → Celsius', run: ({ argv }) => { const [f] = nums(argv); if (f == null) throw new Error('Usage: `?f2c 68`'); return `🌡️ ${f}°F = **${((f - 32) * 5 / 9).toFixed(1)}°C**`; } },
  { name: 'mi2km', category: 'qmath', description: 'Miles → kilometers', run: ({ argv }) => { const [m] = nums(argv); if (m == null) throw new Error('Usage: `?mi2km 5`'); return `📏 ${m} mi = **${(m * 1.60934).toFixed(2)} km**`; } },
  { name: 'km2mi', category: 'qmath', description: 'Kilometers → miles', run: ({ argv }) => { const [k] = nums(argv); if (k == null) throw new Error('Usage: `?km2mi 5`'); return `📏 ${k} km = **${(k / 1.60934).toFixed(2)} mi**`; } },
  { name: 'kg2lb', category: 'qmath', description: 'Kilograms → pounds', run: ({ argv }) => { const [k] = nums(argv); if (k == null) throw new Error('Usage: `?kg2lb 70`'); return `⚖️ ${k} kg = **${(k * 2.20462).toFixed(1)} lb**`; } },
  { name: 'lb2kg', category: 'qmath', description: 'Pounds → kilograms', run: ({ argv }) => { const [l] = nums(argv); if (l == null) throw new Error('Usage: `?lb2kg 150`'); return `⚖️ ${l} lb = **${(l / 2.20462).toFixed(1)} kg**`; } },
  { name: 'roman', category: 'qmath', description: 'Number → Roman numerals', run: ({ argv }) => { let n = nums(argv)[0]; if (n == null || n < 1 || n > 3999) throw new Error('Give 1–3999.'); let out = ''; for (const [v, s] of ROMANS) while (n >= v) { out += s; n -= v; } return `🏛️ **${out}**`; } },
  { name: 'unroman', category: 'qmath', description: 'Roman numerals → number', run: ({ args }) => { const s = need(args, '?unroman <numeral>').toUpperCase(); const map = { I: 1, V: 5, X: 10, L: 50, C: 100, D: 500, M: 1000 }; let t = 0; for (let i = 0; i < s.length; i++) { const c = map[s[i]]; if (!c) throw new Error('Invalid numeral.'); t += c < map[s[i + 1]] ? -c : c; } return `🔢 **${t}**`; } },
  { name: 'factorial', aliases: ['fact!'], category: 'qmath', description: 'n! factorial', run: ({ argv }) => { const n = nums(argv)[0]; if (n == null || n < 0 || n > 170) throw new Error('Give 0–170.'); let r = 1; for (let i = 2; i <= n; i++) r *= i; return `❗ ${n}! = **${r}**`; } },
  { name: 'isprime', category: 'qmath', description: 'Is a number prime?', run: ({ argv }) => { const n = nums(argv)[0]; if (n == null || n < 1) throw new Error('Give a positive integer.'); let p = n > 1; for (let i = 2; i * i <= n; i++) if (n % i === 0) { p = false; break; } return `${p ? '✅' : '❌'} ${n} is ${p ? '' : 'not '}prime.`; } },
  { name: 'fib', category: 'qmath', description: 'Nth Fibonacci number', run: ({ argv }) => { const n = nums(argv)[0]; if (n == null || n < 0 || n > 90) throw new Error('Give 0–90.'); let [a, b] = [0, 1]; for (let i = 0; i < n; i++) [a, b] = [b, a + b]; return `🔢 fib(${n}) = **${a}**`; } },
  { name: 'gcd', category: 'qmath', description: 'Greatest common divisor', run: ({ argv }) => { let [a, b] = nums(argv); if (a == null || b == null) throw new Error('Usage: `?gcd 12 18`'); [a, b] = [Math.abs(a), Math.abs(b)]; while (b) [a, b] = [b, a % b]; return `🔗 GCD = **${a}**`; } },
  { name: 'hex', category: 'qmath', description: 'Decimal → hexadecimal', run: ({ argv }) => { const n = nums(argv)[0]; if (n == null) throw new Error('Usage: `?hex 255`'); return `🔟 ${n} = **0x${n.toString(16).toUpperCase()}**`; } },
  { name: 'unhex', category: 'qmath', description: 'Hexadecimal → decimal', run: ({ args }) => { const s = need(args, '?unhex <hex>').replace(/^0x/i, ''); const n = parseInt(s, 16); if (Number.isNaN(n)) throw new Error('Bad hex.'); return `🔟 0x${s.toUpperCase()} = **${n}**`; } },
  { name: 'dec2bin', category: 'qmath', description: 'Decimal → binary', run: ({ argv }) => { const n = nums(argv)[0]; if (n == null) throw new Error('Usage: `?dec2bin 10`'); return `💾 ${n} = **${n.toString(2)}**`; } },
  { name: 'bin2dec', category: 'qmath', description: 'Binary → decimal', run: ({ args }) => { const s = need(args, '?bin2dec <bits>'); const n = parseInt(s, 2); if (Number.isNaN(n)) throw new Error('Bad binary.'); return `💾 ${s} = **${n}**`; } },
  { name: 'tip', category: 'qmath', description: '?tip 50 18 → tip on a bill', run: ({ argv }) => { const [bill, p = 15] = nums(argv); if (bill == null) throw new Error('Usage: `?tip <bill> [pct]`'); const t = bill * p / 100; return `💵 ${p}% tip on ${bill} = **${t.toFixed(2)}** (total **${(bill + t).toFixed(2)}**)`; } },

  // ---------------- FUN (category: qfun) ----------------
  { name: '8ball', aliases: ['8b'], category: 'qfun', description: 'Ask the magic 8-ball', run: ({ args }) => { need(args, '?8ball <question>'); return `🎱 ${pick(['It is certain.', 'Without a doubt.', 'Yes — definitely.', 'Most likely.', 'Ask again later.', 'Cannot predict now.', "Don't count on it.", 'My reply is no.', 'Very doubtful.', 'Outlook not so good.'])}`; } },
  { name: 'coin', aliases: ['flip', 'coinflip'], category: 'qfun', description: 'Flip a coin', run: () => `🪙 **${pick(['Heads', 'Tails'])}**!` },
  { name: 'choose', aliases: ['pick'], category: 'qfun', description: 'Pick from options (comma-separated)', run: ({ args }) => { const opts = need(args, '?choose a, b, c').split(',').map((s) => s.trim()).filter(Boolean); if (opts.length < 2) throw new Error('Give at least 2 options separated by commas.'); return `🤔 I choose **${pick(opts)}**!`; } },
  { name: 'rps', category: 'qfun', description: 'Rock–paper–scissors vs the bot', run: ({ argv }) => { const you = (argv[0] || '').toLowerCase(); const set = ['rock', 'paper', 'scissors']; if (!set.includes(you)) throw new Error('Pick rock, paper, or scissors.'); const me = pick(set); const win = { rock: 'scissors', paper: 'rock', scissors: 'paper' }; const res = you === me ? "It's a tie!" : win[you] === me ? 'You win! 🎉' : 'I win! 😎'; return `You: ${you} • Me: ${me} → **${res}**`; } },
  { name: 'ship', category: 'qfun', description: '?ship A B → love calculator', run: ({ argv }) => { if (argv.length < 2) throw new Error('Usage: `?ship <a> <b>`'); const seed = [...argv.join('')].reduce((a, c) => a + c.charCodeAt(0), 0); const pctv = seed % 101; return `💘 **${argv[0]} + ${argv[1]}** = ${pctv}% ${pctv > 70 ? '❤️' : pctv > 40 ? '💛' : '💔'}`; } },
  { name: 'rate', category: 'qfun', description: 'Rate anything out of 10', run: ({ args }) => { const s = need(args, '?rate <thing>'); const seed = [...s].reduce((a, c) => a + c.charCodeAt(0), 0); return `⭐ I rate **${s}** a **${seed % 11}/10**.`; } },
  { name: 'iq', category: 'qfun', description: 'Measure someone’s "IQ"', run: ({ args, message }) => `🧠 ${args || message.author.username} has an IQ of **${rint(55, 160)}**.` },
  { name: 'simp', aliases: ['howsimp'], category: 'qfun', description: 'Simp meter', run: ({ args, message }) => `😳 ${args || message.author.username} is **${rint(0, 100)}%** simp.` },
  { name: 'vibe', category: 'qfun', description: 'Vibe check', run: ({ message }) => `${pick(['✅ Vibe check passed!', '❌ Vibe check FAILED.', '🌊 Immaculate vibes.', '😐 Mid vibes, honestly.'])} — ${message.author.username}` },
  { name: 'decide', aliases: ['yn'], category: 'qfun', description: 'Yes or no?', run: () => pick(['✅ Yes.', '❌ No.', '🤷 Maybe.', '💯 Absolutely.', '🚫 Absolutely not.']) },
  { name: 'roast', category: 'qfun', description: 'Get a light-hearted roast', run: ({ args, message }) => `🔥 ${args || message.author.username}, ${pick(['you bring everyone so much joy… when you leave the room.', 'your secrets are safe with me — I never even listen.', "you have something on your chin… no, the third one down.", "if laughter is the best medicine, your face is curing the whole server.", "you're not stupid; you just have bad luck thinking."])}` },
  { name: 'compliment', aliases: ['nice'], category: 'qfun', description: 'Get a wholesome compliment', run: ({ args, message }) => `💖 ${args || message.author.username}, ${pick(['you light up every channel you post in.', 'your energy is genuinely contagious.', "you're the reason this server smiles.", 'you make hard things look easy.', 'the world is better with you in it.'])}` },
  { name: 'pickup', aliases: ['rizz'], category: 'qfun', description: 'A cheesy pickup line', run: () => `😏 ${pick(['Are you a magician? Because whenever I look at you, everyone else disappears.', "Do you have a map? I keep getting lost in your eyes.", 'Are you Wi-Fi? Because I’m feeling a connection.', "If you were a vegetable you'd be a cute-cumber.", 'Are you made of copper and tellurium? Because you’re Cu-Te.'])}` },
  { name: 'wyr', aliases: ['wouldyourather'], category: 'qfun', description: 'Would you rather…?', run: () => `🤔 Would you rather ${pick(['be able to fly', 'be invisible', 'read minds', 'never sleep again', 'have unlimited money', 'live forever', 'teleport anywhere', 'speak every language'])} **OR** ${pick(['breathe underwater', 'stop time', 'be super strong', 'never eat again', 'know every truth', 'be famous', 'time travel', 'talk to animals'])}?` },
  { name: 'fortune', aliases: ['cookie'], category: 'qfun', description: 'Crack a fortune cookie', run: () => `🥠 ${pick(['A pleasant surprise is waiting for you.', 'Your hard work is about to pay off.', 'Adventure awaits — say yes.', 'The best is yet to come.', 'A small act of kindness will echo far.', 'Good news will come from far away.'])}` },
  { name: 'dadjoke', aliases: ['dad'], category: 'qfun', description: 'A groan-worthy dad joke', run: () => pick(['I’m afraid for the calendar. Its days are numbered.', 'Why don’t skeletons fight each other? They don’t have the guts.', 'I only know 25 letters of the alphabet. I don’t know y.', 'What do you call fake spaghetti? An impasta.', 'I used to hate facial hair… but then it grew on me.']) },
  { name: 'fact', aliases: ['randomfact'], category: 'qfun', description: 'A random fun fact', run: () => `💡 ${pick(['Honey never spoils.', 'Octopuses have three hearts.', 'Bananas are berries; strawberries aren’t.', 'A day on Venus is longer than its year.', 'Wombat poop is cube-shaped.', 'Sharks existed before trees.'])}` },
  { name: 'cowsay', category: 'qfun', description: 'Have a cow say your text', run: ({ args }) => { const t = need(args, '?cowsay <text>').slice(0, 120); const cow = ['        \\   ^__^', '         \\  (oo)\\_______', '            (__)\\       )\\/\\', '                ||----w |', '                ||     ||'].join('\n'); return '```\n ' + '_'.repeat(t.length + 2) + '\n< ' + t + ' >\n ' + '-'.repeat(t.length + 2) + '\n' + cow + '\n```'; } },
  { name: 'slot', aliases: ['slots'], category: 'qfun', description: 'Spin a mini slot machine', run: () => { const e = ['🍒', '🍋', '🔔', '💎', '7️⃣', '🍀']; const r = [pick(e), pick(e), pick(e)]; const win = r[0] === r[1] && r[1] === r[2]; return `🎰 [ ${r.join(' | ')} ] ${win ? '— **JACKPOT!** 🎉' : ''}`; } },

  // ---------------- UTILITY (category: qutil) ----------------
  { name: 'uuid', aliases: ['guid'], category: 'qutil', description: 'Generate a random UUID', run: () => `🆔 \`${globalThis.crypto.randomUUID()}\`` },
  { name: 'password', aliases: ['pw', 'pass'], category: 'qutil', description: 'Generate a strong password', run: ({ argv }) => { const len = Math.min(64, Math.max(6, nums(argv)[0] || 16)); const cs = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*'; let p = ''; for (let i = 0; i < len; i++) p += cs[Math.floor(Math.random() * cs.length)]; return `🔐 ||\`${p}\`||`; } },
  { name: 'color', aliases: ['hexcolor', 'randomcolor'], category: 'qutil', description: 'Random hex color', run: () => { const h = '#' + Math.floor(Math.random() * 0xffffff).toString(16).padStart(6, '0').toUpperCase(); return `🎨 \`${h}\``; } },
  { name: 'random', aliases: ['rng', 'rand'], category: 'qutil', description: 'Random number ?random 1 100', run: ({ argv }) => { const [a = 1, b = 100] = nums(argv); return `🎲 **${rint(Math.min(a, b), Math.max(a, b))}**`; } },
  { name: 'len', aliases: ['length'], category: 'qutil', description: 'Length of your text', run: ({ args }) => `📏 **${[...need(args, '?len <text>')].length}** characters.` },
  { name: 'ascii', category: 'qutil', description: 'Text → ASCII codes', run: ({ args }) => [...need(args, '?ascii <text>')].map((c) => c.charCodeAt(0)).join(' ') },
  { name: 'base64', aliases: ['b64', 'encode'], category: 'qutil', description: 'Encode text to Base64', run: ({ args }) => Buffer.from(need(args, '?base64 <text>')).toString('base64') },
  { name: 'unbase64', aliases: ['unb64', 'decode'], category: 'qutil', description: 'Decode Base64 to text', run: ({ args }) => Buffer.from(need(args, '?unbase64 <b64>'), 'base64').toString('utf8') },
  { name: 'ping', category: 'qutil', description: 'Show the bot’s gateway latency', run: ({ message }) => `🏓 Pong! Gateway ping: **${Math.round(message.client.ws.ping)}ms**` },
  { name: 'urlencode', aliases: ['urlenc'], category: 'qutil', description: 'Percent-encode text for URLs', run: ({ args }) => encodeURIComponent(need(args, '?urlencode <text>')) },
  { name: 'urldecode', aliases: ['urldec'], category: 'qutil', description: 'Decode a percent-encoded URL', run: ({ args }) => decodeURIComponent(need(args, '?urldecode <text>')) },
];

export default COMMANDS;
